In [ ]:
# NUMPY =   Numerical Python, is an open source library available in Python,
#           that aids in mathematical,scientific, engineering and data science programming,
#           memory efficient

In [1]:
import numpy as np
np.__version__

'1.24.3'

In [ ]:
# pip install numpy --upgrade

In [2]:
np_array = np.array([1,2,3,4,5,6,7,8,9,0])
np_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [3]:
x = ([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
np_array = np.array(x)
np_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
 # + - * / ** // %
    
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
np_array = np.array(x)
print(np_array + 5)

[ 6  7  8  9 10 11 12 13 14  5]


In [5]:
print(np_array - 5)
print(np_array * 5)
print(np_array / 5)
print(np_array // 5)
print(np_array ** 5)
print(np_array % 5)

[-4 -3 -2 -1  0  1  2  3  4 -5]
[ 5 10 15 20 25 30 35 40 45  0]
[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 0. ]
[0 0 0 0 1 1 1 1 1 0]
[    1    32   243  1024  3125  7776 16807 32768 59049     0]
[1 2 3 4 0 1 2 3 4 0]


In [7]:
a = np.array([1,2,3,4,5,6,6])
b = np.array([3,7,9,3,4,6,7])
c = a + b
print(c)

[ 4  9 12  7  9 12 13]


In [10]:
#shape of array
a = np.array([1,2,3,4,5,6,6])
print(a.shape)

(7,)


In [19]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a.shape)
print(len(a.shape))

(3, 3)
2


In [23]:
a = np.array([[4,5,6,7],
              [4,5,6],
              [4,5,6,9,9]])
print(a.shape)
print(len(a.shape))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [24]:
a = np.array([[[1],[2],[3]],
              [[4],[5],[6]],
              [[7],[8],[9]]])
print(a.shape)
print(len(a.shape))

(3, 3, 1)
3


In [25]:
a = np.array([[[1,1],[2,4],[3,6]],
              [[4,4],[5,8],[6,8]]])
print(a.shape)
print(len(a.shape))

(2, 3, 2)
3


In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [33]:
np.zeros((3,3))+5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [36]:
np.ones((2,2))-4

array([[-3., -3.],
       [-3., -3.]])

In [37]:
np.ones((2,2))*4

array([[4., 4.],
       [4., 4.]])

In [41]:
np.ones((2,2))/4

array([[0.25, 0.25],
       [0.25, 0.25]])

In [38]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
#reshape
a = np.array([[1,2,4],
            [3,6,8]])

# 2*3 = 6
# 3*2 = 6
# 1*6 = 6
# 6*1 = 6


print(a.shape)
print(a.reshape(3,2))
print(a.reshape(1,6))
print(a.reshape(6,1))

(2, 3)
[[1 2]
 [4 3]
 [6 8]]
[[1 2 4 3 6 8]]
[[1]
 [2]
 [4]
 [3]
 [6]
 [8]]


In [51]:
#concat numpy array 
a = np.array([1,2,3])
b = np.array([4,5,6])

# c = a+b

print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [52]:
#concat numpy array 
a = np.array([1,2,3])
b = np.array([4,5,6])

# c = a+b

print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]
